<!---

# test_compressCSS

Test pad for testing staticFiles compression method

## Synopsis

Create a staticfiles object and load a def file.

Run the compressPackage Method

## Usage

Preview in testing server context.

By default file names are generated by expanding the path of the files. You can add mappings to set the output folder.

You can override this with an output directory supplied to the compressPackage() method. This will
use the last part of the file path. The ExpandPath method is better as it will preserve hierarchies.

A build process would probably also push the files to the cloud or similar.
--->

<cfscript>
local = {};
for (local.opts in ["CSS","JS"]) {
	// defFile = ExpandPath("test_js.json");
	defFile = ExpandPath("../../staticFiles/static#local.opts#.json");
	local.tempData = FileRead(defFile);
	try {
		local.jsonData = deserializeJSON(local.tempData);
	}
	catch (Any e) {
		throw("Unable to parse static files definition file #arguments.defFile#");	
	}

	staticFilesObj = new clikpage.staticFiles.staticFiles(staticDef=local.jsonData);
	local.packages = staticFilesObj.compressPackage(type=local.opts,overwrite=true);

	for (local.res in local.packages) {
		writeDump(local.res);
	}
}

</cfscript>
