<!---

# Test menu styling



## To Do

- [ ] Align - not working in other media
- [ ] Icons - Needs some work. Also the mechanism for applying stying is TBC

--->

<cfscript>
// Style definition -- see link to css file ibid.
settingsDef = ExpandPath("_styles/menu_test_settings.xml")
menuData = ExpandPath("../site/_out/sampleMenu.json");
// End Definitions

settingsObj = new clikpage.settings.settings(debug=1);
contentObj = new clikpage.content.content(settingsObj=settingsObj);
styles = settingsObj.loadStyleSettings(settingsDef);
pageObj = new clikpage.page(debug=1);
menu_cs = contentObj.new(id="menu",title="menu",type="menu");
menu_cs.data = deserializeJSON(FileRead(menuData));

contentObj.debug = 1;

contentObj.settings(menu_cs,styles.style,styles.media);

menuCss = "/* auto generated by menus.cfm test page */" & NewLine();
menuCss &= ":root {\n" &  settingsObj.colorVariablesCSS(settings=styles,debug=contentObj.debug) & "}\n";
site.cs = {
	"menu" = menu_cs
};

menuCss &= contentObj.contentCSS(styles=styles.style,content_sections=site.cs,media=styles.media);

menuCss = settingsObj.outputFormat(
	css=menuCss,
	media=styles.media,
	debug=contentObj.debug
);

FileWrite(ExpandPath("menu_styling.css"),menuCss,"utf-8");

cs = contentObj.display(content=menu_cs);

</cfscript>

<!DOCTYPE html>
<html>
<head>
	<title>Menu test</title>
	<cfoutput>
	#pageObj.cssStaticFiles.getLinks(cs.pagecontent.static_css,1)#
	</cfoutput>
	<link rel="stylesheet" type="text/css" href="/_assets/css/fonts/google_icons_codes.css">
	<link rel="stylesheet" type="text/css" href="/_assets/css/fonts/google_icons.css">
	<link rel="stylesheet" type="text/css" href="/_assets/css/icons.css">
	<link rel="stylesheet" type="text/css" href="menu_styling.css">

	<meta charset="UTF-8">
	<style>
		#menu {
			margin:20px;
		}

		#menu .menu_index  {
			--menu-icon: var(--icon-home);
		}
		#menu .menu_gallery  {
			--menu-icon: var(--icon-search);
		}
		#menu .menu_gallery2  {
			--menu-icon:var(--icon-last_page);
		}
		#menu .menu_about  {
			--menu-icon: var(--icon-favorite);
		}
		#menu .menu_news  {
			--menu-icon: var(--icon-account);
		}
		#menu .menu_newscarousel  {
			--menu-icon: var(--icon-cart);
		}
		#menu .menu_images  {
			--menu-icon: var(--icon-done);
		}
		#menu .menu_singlearticle  {
			--menu-icon: var(--icon-fullscreen_exit);	
	</style>
</head>
<body>

<div class="cs-title">
Menu Testing
</div>

<cfoutput>#cs.html#
 
#pageObj.jsStaticFiles.getLinks(cs.pagecontent.static_js,1)#
</cfoutput>

<script>
$(document).ready(function() {
	<cfoutput>#cs.pagecontent.onready#</cfoutput>
});
</script>

</body>
</html>

