<!---

## Status

WIP converting to formal cs. NB menu.cfc in this folder deprecated.
     
## To Do

- [ ] Align - not working in other media
- [ ] Icons - NB need menu icons and open indicator! Confusion here.

--->

<cfscript>
settingsObj = new clikpage.settings.settings(debug=1);
contentObj = new clikpage.content.content(settingsObj=settingsObj);
styles = settingsObj.loadStyleSheet(ExpandPath("../styles/testStyles.xml"));
pageObj = new clikpage.page(debug=1);
menu_cs = contentObj.new(id="menu",title="menu",type="menu");
menu_cs.data = deserializeJSON(FileRead(ExpandPAth("../site/_out/sampleMenu.json")));

contentObj.debug = 1;

menustyles = {};

menustyles.main = {
	"menu-icon-display": "none",
	"menu-item-padding": "8px",
	"flex": 0,
	"align": "center",
	"menu-gap":"6px",
	"menu-item-border": "0",
	"border-type" :"normal",
	"link-color": "Brown",
	"menu-background": "Bisque",
	"menu-item-border": "0 0 4px 0",
	"hover": {
		"link-color" : "DarkCyan",
		"menu-background" : "DarkKhaki",
		"menu-border-color" : "pink"
	},
	"hi": {
		"link-color" : "Cornsilk",
		"menu-background" : "darkslategray"
	}

}

menustyles.max = {
	"menu-icon-display": "inline-block",
	"align": "right",
	"menu-item-padding": "4px 12px",
	"border-type" :"dividers",
	"menu-gap":"0",
	"menu-item-border": "1px",
	"flex": 1,
	"stretch":0
}


menustyles.mid = {
	"width":"120px",
	"flex": 0,
	"menu-gap":"0",
	"orientation": "vertical",
	"align": "left",
	"menu-item-border": "1px",
	"border-type" :"dividers",
	"submenu_position":"static",
	"menu-icon-display": "inline-block"
}

menustyles.mobile = {
	"width":"48px",
	"flex": 0,
	"menu-gap":"0",
	"orientation": "vertical",
	"align": "left",
	"menu-item-border": "0px",
	"border-type" :"dividers",
	"submenu_position":"static",
	"menu-label-display": "none"
}

styles.content["menu"] = menustyles;


menuCss = "/* auto generated by menus.cfm test page */" & NewLine();

site.cs = {
	"menu" = menu_cs
};

menuCss &= contentObj.contentCSS(styles=styles.content,content_sections=site.cs,media=styles.media);
menuCss = settingsObj.outputFormat(menuCss,styles.media);

FileWrite(ExpandPath("menu_styling.css"),menuCss,"utf-8");

contentObj.settings(menu_cs,styles.content,styles.media);


// writeDump(cmenu_css);

cs = contentObj.display(content=menu_cs);


</cfscript>

<!DOCTYPE html>
<html>
<head>
	<title>Menu test</title>
	<cfoutput>
	#pageObj.cssStaticFiles.getLinks(cs.pagecontent.static_css,1)#
	</cfoutput>
	<link rel="stylesheet" type="text/css" href="/_assets/css/fonts/google_icons_codes.css">
	<link rel="stylesheet" type="text/css" href="/_assets/css/fonts/google_icons.css">
	<link rel="stylesheet" type="text/css" href="/_assets/css/icons.css">
	<link rel="stylesheet" type="text/css" href="menu_styling.css">

	<meta charset="UTF-8">
	<style>
		#menu {
			margin:20px;
		}

		#menu .menu_sample1-1  {
			--menu-icon: var(--icon-home);
		}
		#menu .menu_sample2-1  {
			--menu-icon: var(--icon-search);
		}
		#menu .menu_sample3-1  {
			--menu-icon:var(--icon-last_page);
		}
		#menu .menu_sample4-1  {
			--menu-icon: var(--icon-favorite);
		}
		#menu .menu_sample5-1  {
			--menu-icon: var(--icon-account);
		}
		#menu .menu_sample6-1  {
			--menu-icon: var(--icon-cart);
		}
		#menu .menu_sample7-1  {
			--menu-icon: var(--icon-done);
		}
		#menu .menu_sample8-1  {
			--menu-icon: var(--icon-fullscreen_exit);	
	</style>
</head>
<body>

<div class="cs-title">
Menu Testing
</div>

<cfoutput>#cs.html#

#pageObj.jsStaticFiles.getLinks(cs.pagecontent.static_js,1)#
</cfoutput>


<script>
	
	$(document).ready(function() {
		
		<cfoutput>#cs.pagecontent.onready#</cfoutput>
	
	});

</script>

</body>
</html>

